video_processing:  
  sources:  
    - type: "linux_desktop"  
      path: "/home/benn/CODE/RUGBY/rugby/input_data/08182025"  
      watch_patterns: ["*.MPG", "*.mpg"]  
    - type: "network_host"
      path: "/mnt/nas/rugby_videos/"
      watch_patterns: ["*.mp4", "*.avi", "*.mov"]
    - type: "windows_desktop"
      path: "D:/Rugby/Clips/"
      watch_patterns: ["*.mkv", "*.mp4"]
        
  conversion:  
    ffmpeg:  
      video_codec: "libx264"  
      crf: 23  
      preset: "fast"  
      audio_codec: "aac"  
      audio_bitrate: "128k"  
    parallel_workers: 4  
      
  indexing:  
    ai_provider: "openai"  
    model: "gpt-4o-mini"  
    batch_size: 10
    prompt_model:
      system: |
        You are a video editor AI. Your job is to generate video sequences from clips based on user requests.
      user: |
        {user_request}
      instructions: |
        Use the available clips and context to create a sequence plan. Consider narrative flow, pacing, and the user's intent.
      examples:
        - user: "Create a highlight reel of best tackles."
          assistant: "{...example JSON output...}"

