# Copyright (c) 2025 Biasware LLC
# Proprietary and Confidential. All Rights Reserved.
# This file is the sole property of Biasware LLC.
# Unauthorized use, distribution, or reverse engineering is prohibited.

video_processing:
  sources:
    - type: "linux_desktop"
      path: "./data/raw/videos/test_partition"
      watch_patterns: ["mpg", "mov", "avi", "mkv"]

  conversion:
    ffmpeg:
      video_codec: "libx264"
      crf: 23
      preset: "fast"
      audio_codec: "aac"
      audio_bitrate: "128k"
    parallel_workers: 4

  transcription:
    model_size: "tiny"
    language: "en"
    output_dir: "./data/derived/transcripts"
    preserve_tree: true
    device: "cpu"

  indexing:
    ai_provider: "openai"
    model: "gpt-4o-mini"
    batch_size: 10
    prompt_model:
      system: |
        You are a video editor AI. Your job is to generate video sequences from clips based on user requests.
      user: |
        {user_request}
      instructions: |
        Use the available clips and context to create a sequence plan. Consider narrative flow, pacing, and the user's intent.
      examples:
        - user: "Create a highlight reel of best tackles."
          assistant: "{...example JSON output...}"
