# Copyright (c) 2025 Biasware LLC
# Proprietary and Confidential. All Rights Reserved.
# This file is the sole property of Biasware LLC.
# Unauthorized use, distribution, or reverse engineering is prohibited.

video_processing:
  sources:
    - type: "linux_desktop"
      path: "./data/raw/videos/tester"
      watch_patterns: ["mpg", "mov", "avi", "mkv"]

  conversion:
    ffmpeg:
      video_codec: "libx264"
      crf: 23
      preset: "fast"
      audio_codec: "aac"
      audio_bitrate: "128k"
    parallel_workers: 4

  transcription:
    model_size: "tiny"
    language: "en"
    output_dir: "./data/derived/transcripts"
    preserve_tree: true
    device: "cpu"

  indexing:
    ai_provider: "openai"
    model: "gpt-4o-mini"
    batch_size: 10
    prompt_model:

      system: |
        You are a highly skilled AI assistant specializing in summarizing rugby training sessions.
      user: |
        {user_request}
      instructions: |
        You are an assistant that summarizes transcripts from rugby training sessions.
        The following text is a subtitle transcript extracted from an SRT file.
        It may contain timestamps, filler words, or non-relevant chatter.

        Your task:
        - Ignore timestamps and irrelevant text.
        - Focus only on the rugby training content (coaching instructions, drills, exercises, strategy, and feedback).
        - Provide a concise summary of the training session.
        - If possible, organize the summary into key drills, strategies, and coaching points.
      examples:
        - user: "Create a highlight reel of best tackles."
          assistant: "{...example JSON output...}"
